export const AUTH_ACTIONS = {
  LOG_IN: "LOG_IN"
};

export const ROUTE_ACTIONS = {
  ROUTE_CHANGE : "ROUTE_CHANGE"
}

export const SIDENAV_ACTIONS = {
  OPEN_SIDENAV : "OPEN_SIDENAV",
  CLOSE_SIDENAV : "CLOSE_SIDENAV"
}
