export const USER_MEMBERSHIP_STATUS = {
  NEW_MEMBER: 'NEW_MEMBER',
  BASIC_MEMBER: 'BASIC_MEMBER',
  BRONZE_MEMBER: 'BRONZE_MEMBER',
  SILVER_MEMBER: 'SILVER_MEMBER',
  GOLDEN_MEMBER: 'GOLDEN_MEMBER',
  PLATINUM_MEMBER: 'PLATINUM_MEMBER'
};

export const APP_MODE = {
  BIDDER: 'BIDDER',

};
