export const USER_MEMBERSHIP_STATUS = {
  NEW_MEMBER: 'NEW_MEMBER',
  BASIC_MEMBER: 'BASIC_MEMBER',
  BRONZE_MEMBER: 'BRONZE_MEMBER',
  SILVER_MEMBER: 'SILVER_MEMBER',
  GOLDEN_MEMBER: 'GOLDEN_MEMBER',
  PLATINUM_MEMBER: 'PLATINUM_MEMBER',
};

export const APP_MODE = {
  BIDDER: 'BIDDER',
};

export const USER_MEMBERSHIP_TO_DISPLAY = {
  NEW_MEMBER: 'New Member',
  BASIC_MEMBER: 'Basic Member',
  BRONZE_MEMBER: 'Bronze Member',
  SILVER_MEMBER: 'Silver Member',
  GOLDEN_MEMBER: 'Golden Member',
  PLATINUM_MEMBER: 'Platinum Member',
};

const BIDORBOO_SERVICECHARGE = 0.06;
