export const USER_MEMBERSHIP_STATUS = {
  NEW_MEMBER: 'NEW_MEMBER',
  BASIC_MEMBER: 'BASIC_MEMBER',
  BRONZE_MEMBER: 'BRONZE_MEMBER',
  SILVER_MEMBER: 'SILVER_MEMBER',
  GOLDEN_MEMBER: 'GOLDEN_MEMBER',
  PLATINUM_MEMBER: 'PLATINUM_MEMBER',
};

export const APP_MODE = {
  BIDDER: 'BIDDER',
};

export const USER_MEMBERSHIP_TO_DISPLAY = {
  NEW_MEMBER: 'New User',
  ONBOARDED_MEMBER: 'New User',
  VERIFIED_MEMBER: 'Verified User',
  BRONZE_MEMBER: 'Bronse User',
  SILVER_MEMBER: 'Silver User',
  GOLDEN_MEMBER: 'Gold User',
  PLATINUM_MEMBER: 'Platinum User',
};

export const BIDORBOO_SERVICECHARGE_FOR_REQUESTER = 0.06;
