const assert = require('assert');
const mongoose = require('mongoose');

describe('Creating records', () => {
  // it('test stuff ', async (done) => {
  //   assert(1 === 1);
  //   const UserModel = mongoose.model('UserModel');
  //   const findpeople = await UserModel.findOneAndUpdate(
  //     {
  //       _id: { $in: ['5d532b53de8b1605049ed148'] },
  //     },
  //     { $pull: { _postedBidsRef: { $in: ['5d5389c9ebcf2c272414317a'] } } }
  //   )
  //     .lean()
  //     .exec();
  //   console.log(findpeople);
  //   done();
  // });

  it('create jobs ', async (done) => {
    // assert(1 === 1);
    // done();
    const { jobDataAccess } = require('../data-access/jobDataAccess');

    const UserModel = mongoose.model('UserModel');
    const findpeople = await UserModel.find()
      .lean()
      .exec();
    if (findpeople.length > 0) {
      const { _id } = findpeople[0];
      console.log(_id);

      try {
        const { _id } = await jobDataAccess.addAJob(
          {
            detailedDescription: '*generated by test, generated by test',
            location: {
              type: 'Point',
              coordinates: [-75.67933, 45.41451],
            },
            startingDateAndTime: '2019-08-29T21:00:00.000Z',
            addressText: 'Windsor Arms Apartments, 150 Argyle Ave, Ottawa, ON K2P 1B7, Canada',
            templateId: 'bdbHouseCleaning',
            extras: {
              timeOfDay: 'evening',
              effort: 'medium',
            },
            taskImages: [],
          },
          _id
        );
        assert(!!_id);
        done();
      } catch (e) {
        console.log(e);
        assert(1 === 2);
        done();
      }
    }

    assert(1 === 2);
    done();
  });
});
