const mongoose = require('mongoose');
const { Schema } = mongoose;
const mongooseLeanVirtuals = require('mongoose-lean-virtuals');

const BidSchema = new Schema(
  {
    _bidderRef: {
      type: Schema.Types.ObjectId,
      ref: 'UserModel',
      required: true,
    },
    _jobRef: { type: Schema.Types.ObjectId, ref: 'JobModel', required: true }, //we will use this to reference the job
    state: {
      type: String,
      enum: [
        'OPEN',
        'CANCELED_OPEN',
        'CANCELED_CUZ_OF_REQUESTER',
        'CANCELED_BY_BIDDER',
        'WON',
        'WON_SEEN',
      ],
      default: 'OPEN',
    },
    isNewBid: { type: Boolean, default: true }, // will be used to highlight unseen bids
    bidAmount: {
      value: { type: Number, required: true },
      currency: {
        type: String,
        enum: ['CAD', 'USD'],
        default: 'CAD',
      },
    }, //dolar amount
    extras: { type: Object },
  },
  { timestamps: true } // createdAt and updatedAt auto  generated by mongoose
);

BidSchema.virtual('displayStatus').get(function() {
  const stateToDisplayName = {
    OPEN: 'Awaiting On Requester',
    WON: 'Awarded, Tasker is Assigned to the job',
    WON_SEEN: 'Awarded, Tasker is Assigned to the job',
    CANCELED_CUZ_OF_REQUESTER: 'Requester Cancelled the Agreement',
    CANCELED_BY_BIDDER: 'Tasker Cancelled the Agreement',
    CANCELED_OPEN: 'Canceled Bid',
    DONE: 'Task is Completed',
  };
  return stateToDisplayName[this.state];
});
BidSchema.plugin(mongooseLeanVirtuals);

//no need for index on these . avoid performance slowness
mongoose.model('BidModel', BidSchema);
