const GeoJSON = require('mongoose-geojson-schema');
const mongoose = require('mongoose');
const { Schema } = mongoose;

const PropertySchema = new Schema({
  fieldType: String, // in the future make it enum [ 'address field' , fone number ... date ..etc]
  fieldValue: Object,
});

const StatsSchema = new Schema({
  minbid: Number, // in the future make it enum [ 'address field' , fone number ... date ..etc]
  avg: Number,
  max: Number,
  recommended: String, //reference to the ideal bid which is =  $bid amount /bidder's rating
});

const DateTimeSchema = new Schema({
  date: Date,
  hours: Number,
  minutes: Number,
  period: String,
});

const ReviewSchema = new Schema(
  {
    proposerReviewIsDone: { type: Boolean, default: false },
    bidderReviewIsDone: { type: Boolean, default: false },
  },
  { timestamps: true } // createdAt and updatedAt auto generated by mongoose
);

// _props are reference properties
const JobSchema = new Schema(
  {
    _ownerRef: { type: Schema.Types.ObjectId, ref: 'UserModel', required: true },
    ownerId: { type: String, required: true },
    _bidsListRef: [{ type: Schema.Types.ObjectId, ref: 'BidModel' }],
    bidderIds: [{ type: String }],
    title: String,
    state: {
      type: String,
      default: 'OPEN',
      enum: ['OPEN', 'AWARDED', 'DONE', 'CANCELED', 'REOPENED', 'PASTDUE'], //past to represent bids that out dated
    },
    hideForUserIds: [{ type: String }], //array of people who saw this/booed no longer wish to see it ..etc
    properties: [PropertySchema], //list of props needed for a the template
    detailedDescription: { type: String, trim: true },
    stats: StatsSchema,
    awardedBid: {
      type: Schema.Types.ObjectId,
      ref: 'BidModel',
    },
    jobReview: ReviewSchema, //review for each job
    extras: { type: Object, default: null },
    // this is how you create address
    //  point: {
    //   type: "Point",
    //   coordinates: [12.123456, 13.134578]
    // },
    location: { type: mongoose.Schema.Types.Point, index: '2dsphere' },
    addressText: { type: String, trim: true },
    startingDateAndTime: DateTimeSchema,
    durationOfJob: { type: String, trim: true },
    fromTemplateId: { type: String, trim: true },
    reportThisJob: { type: Number },
  },
  { timestamps: true } // createdAt and updatedAt auto generated by mongoose
);

// comment back in if the location search fails
// JobSchema.index({location: '2dsphere'}); //TODO xxx not sure if we need this

//no need for index on these . avoid performance slowness
mongoose.model('JobModel', JobSchema);
