// const mongoose = require('mongoose');
// const { Schema } = mongoose;

// const PaymentSchema = new Schema(
//   {
//     _jobRef: { type: Schema.Types.ObjectId, ref: 'JobModel', required: true },
//     _from: { type: Schema.Types.ObjectId, ref: 'UserModel', required: true },
//     _to: { type: Schema.Types.ObjectId, ref: 'UserModel', required: true },
//     stripeTransId: String,
//     state: String,
//     paymentDetails: {
//       proposerPayment: { type: Number, required: true },
//       bidOrBooCommission: { type: Number, required: true },
//       taskerEarns: { type: Number, required: true },
//       stripeCommission: { type: Number, required: true },
//       currency: String,
//     },
//   },
//   { timestamps: true } // createdAt and updatedAt auto  generated by mongoose
// );

// //no need for index on these . avoid performance slowness
// mongoose.model('PaymentModel', PaymentSchema);
