const mongoose = require('mongoose');
const { Schema } = mongoose;

const categories = {
  type: { category: String, rating: Number },
  enum: ['ACCURACY_OF_POST', 'QUALITY_OF_WORK', 'PUNCTULAITY', 'MANNERS', 'COMMUNICATION'],
};
const ReviewSchema = new Schema(
  {
    jobId: { type: Schema.Types.ObjectId, ref: 'JobModel' },
    bidderId: { type: Schema.Types.ObjectId, ref: 'UserModel' },
    proposerId: { type: Schema.Types.ObjectId, ref: 'UserModel' },
    proposerReview: {
      type: {
        ratingCategories: [{ type: categories }],
        personalComment: String, //max 100 chars
      },
    },
    bidderReview: {
      type: {
        ratingCategories: [{ type: categories }],
        personalComment: String, //max 120 chars
      },
    },
    proposerSubmitted: { type: Boolean, default: false },
    bidderSubmitted: { type: Boolean, default: false },
    reveal: { type: Boolean, default: false }, //this wil turn true only when both completed the review
    extras: { type: Object },
  },
  { timestamps: true } // createdAt and updatedAt auto generated by mongoose
);

ReviewSchema.pre('update', async function(next) {
  if (this.proposerSubmitted && this.bidderSubmitted) {
    this.reveal = true;
  }
  next();
});

//no need for index on these . avoid performance slowness
mongoose.model('ReviewModel', ReviewSchema);
