const mongoose = require('mongoose');
const { Schema } = mongoose;
require('mongoose-type-email');

const MAX_PARAGRAPH_LENGTH = 500;
const MAX_NAME_LENGTH = 50;

const ratingSchema = {
  globalRating: { type: String, default: 'No Ratings Yet' },
  fulfilledBids: { type: Number, default: 0 },
  cancelledBis: { type: Number, default: 0 },
  fulfilledJobs: { type: Number, default: 0 },
  canceledJobs: { type: Number, default: 0 },
};

const UserSchema = new Schema(
  {
    _postedJobsRef: {
      type: [{ type: Schema.Types.ObjectId, ref: 'JobModel' }],
    }, //list of all jobs you have posted
    _postedBidsRef: {
      type: [{ type: Schema.Types.ObjectId, ref: 'BidModel' }],
    }, // list of all bids you made
    _asBidderReviewsRef: [{ type: Schema.Types.ObjectId, ref: 'ReviewModel' }],
    _asProposerReviewsRef: [{ type: Schema.Types.ObjectId, ref: 'ReviewModel' }],
    globalRating: ratingSchema,
    userId: {
      type: String,
      lowercase: true,
      trim: true,
      index: true,
      unique: true,
      required: true,
    },
    email: {
      type: mongoose.SchemaTypes.Email,
      allowBlank: true,
      lowercase: true,
      trim: true,
      index: true,
      unique: true,
    },
    displayName: {
      type: String,
      trim: true,
      maxlength: MAX_NAME_LENGTH,
    },
    phoneNumber: {
      type: String,
      trim: true,
      unique: true,
    },
    profileImage: {
      url: { type: String, default: 'https://goo.gl/92gqPL' },
      public_id: { type: String },
    },
    addressText: { type: String, maxlength: MAX_PARAGRAPH_LENGTH },
    // skills: [String], // list of strings representing their skills
    personalParagraph: { type: String, maxlength: MAX_PARAGRAPH_LENGTH }, // a blob about who they are
    // paymentRefs: [String], // ID to fetch their payments through our system to generate an invoice
    membershipStatus: {
      type: String,
      enum: [
        'NEW_MEMBER',
        'BASIC_MEMBER',
        'BRONZE_MEMBER',
        'SILVER_MEMBER',
        'GOLDEN_MEMBER',
        'PLATINUM_MEMBER',
      ],
      default: 'NEW_MEMBER',
    },
    userRole: {
      type: String,
      enum: ['ADMIN', 'REGULAR'],
      default: 'REGULAR',
    },
    agreedToServiceTerms: { type: Boolean, required: true, default: false },
    settings: { type: Object },
    extras: { type: Object },
    isVerified: { type: Boolean, default: false },
    verificationIdImage: { type: String },
    canBid: { type: Boolean, default: true },
    canPost: { type: Boolean, default: true },
  },
  { timestamps: true } // createdAt and updatedAt auto  generated by mongoose
);

//no need for index on these . avoid performance slowness
mongoose.model('UserModel', UserSchema);
