//to prepend on any async ation that will generate a promise
export const _REJECTED = '_REJECTED';
export const _PENDING = '_PENDING';
export const _FULFILLED = '_FULFILLED';

export const AUTH_ACTIONS = {
  REGISTER_NEW_USER: 'REGISTER_NEW_USER',
  LOGIN_FLOW_INITIATED: 'LOGIN_FLOW_INITIATED',
  USER_IS_LOGGED_IN: 'USER_IS_LOGGED_IN',
  LOGOUT_FLOW_INITIATED: 'LOGOUT_FLOW_INITIATED',
  USER_IS_LOGGED_OUT: 'USER_IS_LOGGED_OUT',
  VERIFY_USER_EMAIL: 'VERIFY_USER_EMAIL',
  VERIFY_USER_PHONE: 'VERIFY_USER_PHONE',
};

export const UI_ACTIONS = {
  OPEN_SIDENAV: 'OPEN_SIDENAV',
  CLOSE_LOGIN_DIALOG: 'CLOSE_LOGIN_DIALOG',
  OPEN_LOGIN_DIALOG: 'OPEN_LOGIN_DIALOG',
  SHOW_TOAST_MSG: 'SHOW_TOAST_MSG',
  SHOW_SPECIAL_MOMENT: 'SHOW_SPECIAL_MOMENT',
  SET_APP_TASKER_VIEW: 'SET_APP_TASKER_VIEW',
  SET_APP_REQUESTER_VIEW: 'SET_APP_REQUESTER_VIEW',
};

export const USER_MODEL_ACTIONS = {
  UPDATE_USER_NOTIFICATION_SETTINGS: 'UPDATE_USER_NOTIFICATION_SETTINGS',
  UPDATE_USER_ON_BOARDING_DETAILS: 'UPDATE_USER_ON_BOARDING_DETAILS',
  UPDATE_USER_APP_VIEW_TO_TASKER: 'UPDATE_USER_APP_VIEW_TO_TASKER',
  UPDATE_USER_APP_VIEW_TO_REQUESTER: 'UPDATE_USER_APP_VIEW_TO_REQUESTER',
  GET_MY_PAST_REQUESTED_SERVICES: 'GET_MY_PAST_REQUESTED_SERVICES',
  GET_MY_PAST_PROVIDED_SERVICES: 'GET_MY_PAST_PROVIDED_SERVICES',
  GET_OTHER_USER_PROFILE_INFO: 'GET_OTHER_USER_PROFILE_INFO',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_IMAGE: 'UPDATE_USER_IMAGE',
  SET_CURRENT_USER_DETAILS: 'SET_CURRENT_USER_DETAILS',
  GET_MY_STRIPE_ACCOUNT_DETAILS: 'GET_MY_STRIPE_ACCOUNT_DETAILS',
};

export const REQUEST_ACTIONS = {
  GET_ALL_MY_REQUESTS: 'GET_ALL_MY_REQUESTS',
  GET_MY_REQUESTS_SUMMARY: 'GET_MY_REQUESTS_SUMMARY',
  GET_ALL_POSTED_REQUESTS: 'GET_ALL_POSTED_REQUESTS',
  GET_ALL_POSTED_REQUESTS_VIA_SEARCH: 'GET_ALL_POSTED_REQUESTS_VIA_SEARCH',
  GET_POSTED_REQUEST_AND_BIDS_FOR_REQUESTER: 'GET_POSTED_REQUEST_AND_BIDS_FOR_REQUESTER',
  GET_ARCHIVED_REQUEST_DETAILS_FOR_REQUESTER: 'GET_ARCHIVED_REQUEST_DETAILS_FOR_REQUESTER',
  GET_REQUEST_To_BID_ON_DETAILS_BY_ID: 'GET_REQUEST_To_BID_ON_DETAILS_BY_ID',
  GET_AWARDED_REQUEST_FULL_DETAILS_FOR_REQUESTER: 'GET_AWARDED_REQUEST_FULL_DETAILS_FOR_REQUESTER',
  DELETE_REQUEST_BY_ID: 'DELETE_REQUEST_BY_ID',
  UPDATE_EXISTING_REQUEST: 'UPDATE_EXISTING_REQUEST',
  ADD_NEW_REQUEST: 'ADD_NEW_REQUEST',
  SELECT_ACTIVE_POSTED_REQUEST: 'SELECT_ACTIVE_POSTED_REQUEST',
  SELECT_ARCHIVE_REQUEST: 'SELECT_ARCHIVE_REQUEST',

  AWARD_TASKER: 'AWARD_TASKER',
  SELECT_AWARDED_REQUEST: 'SELECT_AWARDED_REQUEST',
  REQUEST_MARK_BID_AS_SEEN: 'REQUEST_MARK_BID_AS_SEEN',
  MARK_BID_AS_SEEN: 'MARK_BID_AS_SEEN',
  UPDATE_REQUEST_VIEWED_BY: 'UPDATE_REQUEST_VIEWED_BY',
  UPDATE_REQUEST_BOOED_BY: 'UPDATE_REQUEST_BOOED_BY',
  REQUESTER_CONFIRMS_REQUEST_COMPLETION: 'REQUESTER_CONFIRMS_REQUEST_COMPLETION',
  TASKER_CONFIRMS_REQUEST_COMPLETION: 'TASKER_CONFIRMS_REQUEST_COMPLETION',
  TASKER_DISPUTES_REQUEST: 'TASKER_DISPUTES_REQUEST',
  REQUESTER_DISPUTES_REQUEST: 'REQUESTER_DISPUTES_REQUEST',
  UPDATE_REQUEST_STATE: 'UPDATE_REQUEST_STATE',
};

export const TASKER_ACTIONS = {
  SELECT_REQUEST_TO_BID_ON: 'SELECT_REQUEST_TO_BID_ON',
  POST_A_BID: 'POST_A_BID',
  UPDATE_A_BID: 'UPDATE_A_BID',
  GET_ALL_MY_POSTED_BIDS_SUMMARY: 'GET_ALL_MY_POSTED_BIDS_SUMMARY',
  GET_OPEN_BID_DETAILS: 'GET_OPEN_BID_DETAILS',
  GET_AWARDED_BID_DETAILS: 'GET_AWARDED_BID_DETAILS',
  UPDATE_BID_STATE: 'UPDATE_BID_STATE',
  DELETE_AN_OPEN_BID: 'DELETE_AN_OPEN_BID',
  CANCEL_MY_AWARDED_BID: 'CANCEL_MY_AWARDED_BID',
  GET_ARCHIVED_BID_DETAILS_FOR_TASKER: 'GET_ARCHIVED_BID_DETAILS_FOR_TASKER',
  SELECT_ARCHIVED_BID: 'SELECT_ARCHIVED_BID',
};

export const REQUESTER_ACTIONS = {
  AWARD_TASKER_AND_MAKE_A_PAYMENT: 'AWARD_TASKER_AND_MAKE_A_PAYMENT',
};

export const PAYMENT_ACTIONS = {};
