//to prepend on any async ation that will generate a promise
export const _REJECTED = '_REJECTED';
export const _PENDING = '_PENDING';
export const _FULFILLED = '_FULFILLED';

export const AUTH_ACTIONS = {
  GOOGLE_LOGIN_FLOW_INITIATED: 'GOOGLE_LOGIN_FLOW_INITIATED',
  USER_IS_LOGGED_IN: 'USER_IS_LOGGED_IN',
  LOGOUT_FLOW_INITIATED: 'LOGOUT_FLOW_INITIATED'
};

export const ROUTE_ACTIONS = {
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE'
};

export const UI_ACTIONS = {
  OPEN_SIDENAV: 'OPEN_SIDENAV',
  CLOSE_SIDENAV: 'CLOSE_SIDENAV',
  CLOSE_LOGIN_DIALOG: 'CLOSE_LOGIN_DIALOG',
  OPEN_LOGIN_DIALOG: 'OPEN_LOGIN_DIALOG'
};
