//to prepend on any async ation that will generate a promise
export const _REJECTED = '_REJECTED';
export const _PENDING = '_PENDING';
export const _FULFILLED = '_FULFILLED';

export const AUTH_ACTIONS = {
  REGISTER_NEW_USER: 'REGISTER_NEW_USER',
  LOGIN_FLOW_INITIATED: 'LOGIN_FLOW_INITIATED',
  USER_IS_LOGGED_IN: 'USER_IS_LOGGED_IN',
  LOGOUT_FLOW_INITIATED: 'LOGOUT_FLOW_INITIATED',
  USER_IS_LOGGED_OUT: 'USER_IS_LOGGED_OUT',
};

export const UI_ACTIONS = {
  OPEN_SIDENAV: 'OPEN_SIDENAV',
  CLOSE_LOGIN_DIALOG: 'CLOSE_LOGIN_DIALOG',
  OPEN_LOGIN_DIALOG: 'OPEN_LOGIN_DIALOG',
  SHOW_TOAST_MSG: 'SHOW_TOAST_MSG',
  GET_CURRENT_USER_NOTIFICATIONS: 'GET_CURRENT_USER_NOTIFICATIONS',
  SET_APP_BIDDER_VIEW: 'SET_APP_BIDDER_VIEW',
  SET_APP_PROPOSER_VIEW: 'SET_APP_PROPOSER_VIEW',
};

export const USER_MODEL_ACTIONS = {
  UPDATE_USER_NOTIFICATION_SETTINGS: 'UPDATE_USER_NOTIFICATION_SETTINGS',
  UPDATE_USER_ON_BOARDING_DETAILS: 'UPDATE_USER_ON_BOARDING_DETAILS',
  UPDATE_USER_APP_VIEW_TO_BIDDER: 'UPDATE_USER_APP_VIEW_TO_BIDDER',
  UPDATE_USER_APP_VIEW_TO_PROPOSER: 'UPDATE_USER_APP_VIEW_TO_PROPOSER',
  GET_MY_PAST_REQUESTED_SERVICES: 'GET_MY_PAST_REQUESTED_SERVICES',
  GET_MY_PAST_PROVIDED_SERVICES: 'GET_MY_PAST_PROVIDED_SERVICES',
  GET_OTHER_USER_PROFILE_INFO: 'GET_OTHER_USER_PROFILE_INFO',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  UPDATE_USER_IMAGE: 'UPDATE_USER_IMAGE',
  SET_CURRENT_USER_DETAILS: 'SET_CURRENT_USER_DETAILS',
  GET_MY_STRIPE_ACCOUNT_DETAILS: 'GET_MY_STRIPE_ACCOUNT_DETAILS',
};

export const JOB_ACTIONS = {
  GET_ALL_MY_OPEN_JOBS: 'GET_ALL_MY_OPEN_JOBS',
  GET_ALL_MY_AWARDED_JOBS: 'GET_ALL_MY_AWARDED_JOBS',
  GET_ALL_POSTED_JOBS: 'GET_ALL_POSTED_JOBS',
  GET_POSTED_JOB_DETAILS_BY_ID: 'GET_POSTED_JOB_DETAILS_BY_ID',
  GET_JOB_To_BID_ON_DETAILS_BY_ID: 'GET_JOB_To_BID_ON_DETAILS_BY_ID',
  GET_JOB_FULL_DETAILS_BY_ID: 'GET_JOB_FULL_DETAILS_BY_ID',
  SEARCH_JOB: 'SEARCH_JOB',
  DELETE_JOB_BY_ID: 'DELETE_JOB_BY_ID',
  UPDATE_EXISTING_JOB: 'UPDATE_EXISTING_JOB',
  ADD_NEW_JOB: 'ADD_NEW_JOB',
  SELECT_ACTIVE_POSTED_JOB: 'SELECT_ACTIVE_POSTED_JOB',
  AWARD_BIDDER: 'AWARD_BIDDER',
  SELECT_AWARDED_JOB: 'SELECT_AWARDED_JOB',
  REQUEST_MARK_BID_AS_SEEN: 'REQUEST_MARK_BID_AS_SEEN',
  MARK_BID_AS_SEEN: 'MARK_BID_AS_SEEN',
  UPDATE_JOB_VIEWED_BY: 'UPDATE_JOB_VIEWED_BY',
  UPDATE_JOB_BOOED_BY: 'UPDATE_JOB_BOOED_BY',
  PROPOSER_CONFIRMS_JOB_COMPLETION: 'PROPOSER_CONFIRMS_JOB_COMPLETION',
  BIDDER_CONFIRMS_JOB_COMPLETION: 'BIDDER_CONFIRMS_JOB_COMPLETION',
  BIDDER_DISPUTES_JOB: 'BIDDER_DISPUTES_JOB',
  PROPOSER_DISPUTES_JOB: 'PROPOSER_DISPUTES_JOB',
};

export const BIDDER_ACTIONS = {
  SELECT_JOB_TO_BID_ON: 'SELECT_JOB_TO_BID_ON',
  POST_A_BID: 'POST_A_BID',
  UPDATE_A_BID: 'UPDATE_A_BID',
  GET_ALL_MY_OPEN_BIDS: 'GET_ALL_MY_OPEN_BIDS',
  GET_OPEN_BID_DETAILS: 'GET_OPEN_BID_DETAILS',
  GET_AWARDED_BID_DETAILS: 'GET_AWARDED_BID_DETAILS',
  GET_ALL_MY_AWARDED_BIDS: 'GET_ALL_MY_AWARDED_BIDS',
  UPDATE_BID_STATE: 'UPDATE_BID_STATE',
  DELETE_AN_OPEN_BID: 'DELETE_AN_OPEN_BID',
};

export const PROPOSER_ACTIONS = {
  AWARD_BIDDER_AND_MAKE_A_PAYMENT: 'AWARD_BIDDER_AND_MAKE_A_PAYMENT',
};

export const PAYMENT_ACTIONS = {};
